name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  broken-links:
    name: Check for Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check the links
        uses: lycheeverse/lychee-action@v1
        with:
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}
